apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbpersistent
  namespace: default
spec:
  storageClassName: normal
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi