apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  storageClassName: normal
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfsdrive
    server: 172.31.11.88
