#Namespace Format created by Krishnendu Bhowmick
apiVersion: v1
kind: Namespace
metadata:
  name:  test-ns
---
#ResourceQuota set at Namespace level
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-quota-name
  namespace: test-ns
spec:
  hard:
    requests.cpu: '100m'
    requests.memory: 100Mi
    limits.cpu: '100m'
    limits.memory: 256Mi
---
# LimitRange for Pod or Container
apiVersion: v1
kind: LimitRange
metadata:
  name: apache-test-limitrange
  namespace: test-ns
spec:
  limits:
  # 'default' and 'defaultRequest' may not be specified when type is 'Pod'
  - type: Container
    default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 100m
      memory: 256Mi
    min:
      cpu: 100m
      memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apachetest
  labels:
    app: apachetest
spec:
  selector:
    matchLabels:
      app: apachetest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apachetest
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: apachetest
        image: krishhub/apachetest:1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 80
          name:  apachetest
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: apachetestsvc
spec:
  selector:
    app: apachetest
  type: NodePort
  ports:
  - name: apachetestsvc
    protocol: TCP
    port: 80
    targetPort: 80
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30016
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apachetesthpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apachetest
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
