apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: mongodb-service # has to match .spec.template.metadata.labels
  serviceName: "mongo-headless-service"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: mongodb-service # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo
        command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
        ports:
        - containerPort: 27017
          name: dbport
        volumeMounts:
        - name: mongodbvol
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodbvol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-storageclass"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-headless-service
  namespace: default
spec:
  selector:
    app: mongodb-service
  clusterIP: None
  ports:
  - name: mongoport
    protocol: TCP
    port: 27017
    targetPort: 27017
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
